/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nythr (https://sketchfab.com/dylan.fini)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-alex-character-animated-09835504d17543959d7164353993b9d6
Title: Minecraft Alex Character Animated
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export const Model = (props) => {
  const group = useRef()

  const { nodes, materials, animations } = useGLTF('/models/Girl/scene.gltf')
  const { actions } = useAnimations(animations, group)

  // Mouse position
  const mouse = useRef({ x: 0, y: 0 })

  useEffect(() => {
    const handleMouseMove = (e) => {
      mouse.current.x = (e.clientX / window.innerWidth - 0.5) * 0.4
      mouse.current.y = (e.clientY / window.innerHeight - 0.5) * 0.2
    }

    window.addEventListener('mousemove', handleMouseMove)

    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
    }
  }, [])

  useFrame(() => {
    if (!group.current) return

    // Keep your initial rotation and add a smooth mouse response
    const targetY = (props.rotation?.[1] ?? 0) + mouse.current.x
    const targetX = mouse.current.y

    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      targetY,
      0.08
    )

    group.current.rotation.x = THREE.MathUtils.lerp(
      group.current.rotation.x,
      targetX,
      0.08
    )
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.669}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Alex_18"
                position={[-0.013, 1.24, -0.031]}
                scale={0.62}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Char}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Alex_Mesh_17" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Girl/scene.gltf')

export default Model;
