/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dalopera3D (https://sketchfab.com/Dalopera3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toothless-chimuelo-cute-1d28029000a0461a85832e9d6a4a0ded
Title: Toothless (Chimuelo) cute
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
const Target = (props) => {
  const { nodes, materials } = useGLTF('public/Tmodel/scene.gltf')
  const groupRef = useRef()

  useFrame((state) => {
    if (!groupRef.current) return

    // state.mouse.x and state.mouse.y range from -1 to 1
    const targetRotationY = state.mouse.x * 0.5 // left/right turn amount
    const targetRotationX = -state.mouse.y * 0.3 // up/down tilt amount

    // smoothly interpolate (lerp) toward target rotation for a natural feel
    groupRef.current.rotation.y = THREE.MathUtils.lerp(
      groupRef.current.rotation.y,
      targetRotationY,
      0.20
    )
    groupRef.current.rotation.x = THREE.MathUtils.lerp(
      groupRef.current.rotation.x,
      targetRotationX,
      0.20
    )
    
  })
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cuerpo_low_cuerpo_low0_0.geometry}
          material={materials.cuerpo_low0}
          position={[0, 266.192, 0]}
          scale={178.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['u��as_low_u��as_low0_0'].geometry}
          material={materials.uas_low0}
          position={[0, 266.192, 0]}
          scale={178.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.puas_low_puas_low0_0.geometry}
          material={materials.puas_low0}
          position={[0, 266.192, 0]}
          scale={178.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ojos_low_ojos_low0_0.geometry}
          material={materials.ojos_low0}
          position={[0, 266.192, 0]}
          scale={178.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Diente_low_Diente_low0_0.geometry}
          material={materials.Diente_low0}
          position={[0, 266.192, 0]}
          scale={178.007}
        />
      </group>
    </group>
  )
}

useGLTF.preload('public/Tmodel/scene.gltf')
export default Target;